using Godot;
using Godot.Collections;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

public class CardGenerationContext
{
    public List<Pocket> Pockets { get; set; } = [];
    public Array<BallVariant> BallTiers { get; set; } = [];
    public Random Rng { get; set; }
    public int HopperBallCount { get; set; }
}

public static class CardGenerator
{
    public static CardData GeneratePlayableCard(IEnumerable<Pocket> pockets)
    {
        Debug.Assert(GameConfig.Instance != null, "GameConfig.Instance must not be null");
        Debug.Assert(GameConfig.Instance.BallTiers != null && GameConfig.Instance.BallTiers.Count > 0, "BallTiers must be defined in GameConfig");

        var rollTable = GameConfig.Instance.CardArchetypes;
        Debug.Assert(rollTable != null && rollTable.Count > 0, "CardArchetypes roll table must be configured in GameConfig node");

        var tiers = GameConfig.Instance.BallTiers;
        var rng = GameConfig.Instance.Rng ?? new Random();
        var pocketList = pockets.Where(p => p != null && p.IsInsideTree()).ToList();

        var context = new CardGenerationContext
        {
            Pockets = pocketList,
            BallTiers = tiers,
            Rng = rng,
            HopperBallCount = GetHopperBallCount(pocketList)
        };

        // 1. Query each archetype in the roll table for valid options
        var viableArchetypes = new List<(CardArchetype Archetype, List<CardData> Options, float Weight)>();
        foreach (var archetype in rollTable)
        {
            if (archetype == null) continue;
            var options = archetype.GenerateValidOptions(context);
            if (options != null && options.Count > 0)
            {
                float weight = Mathf.Max(0.01f, archetype.GetWeight(context));
                viableArchetypes.Add((archetype, options, weight));
            }
        }

        // 2. Fallback if no archetype produced options
        if (viableArchetypes.Count == 0)
        {
            var fallbackArchetype = new BallPackArchetype();
            var fallbackOptions = fallbackArchetype.GenerateValidOptions(context);
            if (fallbackOptions != null && fallbackOptions.Count > 0)
            {
                return fallbackOptions[0];
            }
            return null;
        }

        // 3. Roll a valid archetype from the table
        float totalWeight = viableArchetypes.Sum(v => v.Weight);
        double roll = rng.NextDouble() * totalWeight;
        float cumulative = 0.0f;
        var chosenEntry = viableArchetypes[0];

        foreach (var entry in viableArchetypes)
        {
            cumulative += entry.Weight;
            if (roll <= cumulative)
            {
                chosenEntry = entry;
                break;
            }
        }

        // 4. Select one of the valid options generated by that archetype
        int optionIdx = rng.Next(chosenEntry.Options.Count);
        return chosenEntry.Options[optionIdx];
    }

    public static Array<BallVariant> GeneratePackBalls(CardGenerationContext context)
    {
        var validInputs = new List<BallVariant>();
        int maxInputIdx = 0;

        foreach (var pocket in context.Pockets)
        {
            if (pocket == null || !pocket.IsInsideTree() || pocket.InputBalls == null) continue;

            foreach (var ball in pocket.InputBalls)
            {
                if (ball == null) continue;
                if (!validInputs.Contains(ball))
                {
                    validInputs.Add(ball);
                }
                int idx = context.BallTiers.IndexOf(ball);
                if (idx > maxInputIdx)
                {
                    maxInputIdx = idx;
                }
            }
        }

        if (validInputs.Count == 0)
        {
            validInputs.Add(context.BallTiers[0]);
        }

        BallVariant bonusTier = (maxInputIdx + 1 < context.BallTiers.Count) ? context.BallTiers[maxInputIdx + 1] : context.BallTiers[maxInputIdx];
        int packSize = context.Rng.Next(6, 13);
        var packBalls = new Array<BallVariant>();

        for (int i = 0; i < packSize; i++)
        {
            if (context.Rng.NextDouble() < 0.05 && bonusTier != null)
            {
                packBalls.Add(bonusTier);
            }
            else
            {
                int inputIdx = context.Rng.Next(validInputs.Count);
                packBalls.Add(validInputs[inputIdx]);
            }
        }

        return packBalls;
    }

    private static int GetHopperBallCount(List<Pocket> pockets)
    {
        var firstPocket = pockets.FirstOrDefault();
        if (firstPocket != null && firstPocket.IsInsideTree())
        {
            var hoppers = firstPocket.GetTree().GetNodesInGroup("hoppers");
            int total = 0;
            foreach (Node node in hoppers)
            {
                if (node is Hopper hopper && hopper.IsInsideTree())
                {
                    total += hopper.GetTotalBallCount();
                }
            }
            return total;
        }
        return 5;
    }
}
